### ISSUE TITLE
Gem Requirements: firewatir

### ISSUE THREAD

**Issue by m3talsmith** [scrubber/scrubyt#1]
I had the understanding that firewatir was _not_ a requirement in order to use scrubyt for normal scrapes - that firewatir was used for ajax scrapes. Yet I get this when I try requiring scrubyt in irb:

<pre>
irb(main):001:0> require 'rubygems'
=> true
irb(main):002:0> require 'scrubyt'
LoadError: no such file to load -- firewatir
    from /usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from /usr/local/lib/ruby/gems/1.8/gems/scrubyt-0.4.06/lib/scrubyt/core/navigation/agents/firewatir.rb:2
    from /usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from /usr/local/lib/ruby/gems/1.8/gems/scrubyt-0.4.06/lib/scrubyt.rb:29
    from /usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'
    from (irb):2
irb(main):003:0>
</pre>

I actually ran in to this with the latest master, uninstalled that and installed 0.4.06 and still got the above error. Normally I would go ahead and install the required gem but I spent an hour last night trying to get firewatir installed correctly on OS X 10.5.6 to no avail. I'd rather just side step firewatir for now since the majority of things I'm scraping are actually xhtml docs anyways.

**Edit:** This is on Mac OS X 10.6 btw.

**Comment by jakemoffatt** [comment]
Also get this error in ruby 1.8 on windows

**Comment by gtoast** [comment]
I am still seeing this issue. Ruby 1.8.7, OS X 10.6.8.

**Comment by gtoast** [comment]
It looks like all you have to do is install firewatir manually, but if that's the case it seems to me firewatir should become an required dependency so its installed automatically by rubygems. 

_edit_ Scratch that.  still doesn't work because firewatir is also broken. This project may be abandonware. If so someone should just mark it as such.
