### ISSUE TITLE
Fill_textfield: undefined method

### ISSUE THREAD

**Issue by jb-san** [scrubber/scrubyt#2]
I get this error when I try to run any example..

c:/ruby/lib/ruby/gems/1.8/gems/scrubyt-0.4.06/lib/scrubyt/core/navigation/agents/mechanize.rb:178:in `fill_textfield': undefined method`[]=' for nil:NilClass (NoMethodError)

```
    from c:/ruby/lib/ruby/gems/1.8/gems/scrubyt-0.4.06/lib/scrubyt/core/navigation/navigation_actions.rb:27:in `eval'

    from c:/ruby/lib/ruby/gems/1.8/gems/scrubyt-0.4.06/lib/scrubyt/core/navigation/agents/mechanize.rb:178:in `fill_textfield'

    from c:/ruby/lib/ruby/gems/1.8/gems/scrubyt-0.4.06/lib/scrubyt/core/navigation/navigation_actions.rb:27:in `fill_textfield'

    from C:/Documents and Settings/JB/Mina dokument/NetBeansProjects/SBBotbeta1/lib/test1.rb:6

    from c:/ruby/lib/ruby/gems/1.8/gems/scrubyt-0.4.06/lib/scrubyt/core/shared/extractor.rb:75:in `instance_eval'

    from c:/ruby/lib/ruby/gems/1.8/gems/scrubyt-0.4.06/lib/scrubyt/core/shared/extractor.rb:75:in `initialize'

    from c:/ruby/lib/ruby/gems/1.8/gems/scrubyt-0.4.06/lib/scrubyt/core/shared/extractor.rb:32:in `new'

    from c:/ruby/lib/ruby/gems/1.8/gems/scrubyt-0.4.06/lib/scrubyt/core/shared/extractor.rb:32:in `define'
```

I have all the dependencies installed..

**Comment by thooby** [comment]
I have the same problem

**Comment by kaiiserni** [comment]
same problem here

**Comment by gerwinbrunner** [comment]
and here 2

**Comment by kaiiserni** [comment]
Hey all!, 
for me this guide fixed the issue we have: http://www.egeland.net/foswiki/bin/view/Main/ScrubyT

thanks

**Comment by saliem** [comment]
@kaiiserni bu ti dont have ubuntu - i have a mac os

**Comment by kaiiserni** [comment]
Hi saliem, the gem installations in that guide are the solution to this problem (the exact versions). These commands should work on any OS.

**Comment by saliem** [comment]
@kaiiserni ok
